### ISSUE TITLE
raising precision of custom wakeword

### ISSUE THREAD

**Issue by dominickchen** [Ant-Brain/EfficientWord-Net#10]
I'm curious whether the precision of custom wakeword improves if you provide more sound files, e.g. 50 files from different people? or is that meaningless?

We want to use a custom wakeword for a public interaction system, and want it to recognize voice input from a wide range of people (young&old, male&female, etc).

Thank you for letting me know.

**Comment by aman-17** [comment]
Exactly, the more amount of variety in samples, better the model accuracy. And also keep an eye on the threshold, change the value of it according to your requirement.

**Comment by dominickchen** [comment]
Thank you for clarifying! I will try out with about 20 samples to start with and see how it goes.

About the threshold value, it does not seem to be taken into account by the checkFrame method: https://github.com/Ant-Brain/EfficientWord-Net/issues/9#issue-1142751467

**Comment by TheSeriousProgrammer** [comment]
rather than just increasing the samples , consider increasing the variety of the samples that might work
