### ISSUE TITLE
Could you help me?

### ISSUE THREAD

**Issue by preachwebsite** [Ant-Brain/EfficientWord-Net#11]
I won't deploy its running environment. Can you control it remotely? I have TeamViewer, a remote control software. The ID is 621 081 831. Or use other remote control. We look forward to your help.

**Comment by preachwebsite** [comment]
I also have a raspberry pie and don't know how to use it

**Comment by aman-17** [comment]
If you want to use it on RasPi. Firstly, install the dependencies then install our EfficientWord-Net(you can use the pip command for installing). Give the input samples and test your output.

**Comment by TheSeriousProgrammer** [comment]
please remember the reference file of your respective hotword must be generated in x86-64 machine and then deployed in your target system to avoid dependency related issues , since certain binaries arent available for no x86-64 machines
