### ISSUE TITLE
circuit diagram

### ISSUE THREAD

**Issue by preachwebsite** [Ant-Brain/EfficientWord-Net#17]
Good evening！Can you send me the circuit diagram of raspberry pie connecting the bread board and lighting the LED light? Your experiment is so interesting that I want to repeat it.

**Comment by TheSeriousProgrammer** [comment]
You can use this diagram

![image](https://user-images.githubusercontent.com/26043350/160567596-8d8a0588-1600-4741-89e8-99ce218c529b.png)

And use gpio-zero library to control the leds, I dont have access to raspberry pi now. Once obtained will update Readme with circuit diagram and code snipped for raspberry pi

**Comment by preachwebsite** [comment]
OK, thank you for your generous help. Thank you.

**Comment by TheSeriousProgrammer** [comment]
Needs to be added in documentation, Hence reopening

**Comment by preachwebsite** [comment]
Good afternoon！ Can you share the code of GPIO? I encountered some unsolvable problems.

**Comment by TheSeriousProgrammer** [comment]
Try using this https://pypi.org/project/gpiozero/
