### ISSUE TITLE
First person

### ISSUE THREAD

**Issue by preachwebsite** [Ant-Brain/EfficientWord-Net#19]
Good evening. Are you the first to use similarity for wakeup words？

**Comment by TheSeriousProgrammer** [comment]
Hello, to our knowledge amongst opensource hotword detectors, ours is the first to use similarity for hotowords. We are not sure about how the closed source alternatives work

**Comment by TheSeriousProgrammer** [comment]
Can you consider using github discussions page for such queries

**Comment by preachwebsite** [comment]
OK, thank you for your reply！
