### ISSUE TITLE
My performance is bad

### ISSUE THREAD

**Issue by Holly-Max** [Ant-Brain/EfficientWord-Net#25]
Hello, I have the same problem. And I record the video, and i update it to [google drive](https://drive.google.com/file/d/1dodZu3Sb54J-kIYxRZnNVqb7Le9cfXcm/view?usp=share_link). I use python=3.9.13, pyaudio=0.2.11, tflite=2.5.0. Thanks for your help!
![image](https://user-images.githubusercontent.com/60691735/224596167-ee609956-7cde-494e-a1bb-36f036934b7f.png)

**Comment by TheSeriousProgrammer** [comment]
We have added a new model to the flow check it out!!

**Comment by TheSeriousProgrammer** [comment]
Currently closing this issue as the new model should help with the same
