### ISSUE TITLE
Models path is incorrect or not included

### ISSUE THREAD

**Issue by OnlinePage** [Ant-Brain/EfficientWord-Net#28]
hi , I tested the newer model `1.0.1`, it seems like the newer model `Resnet_50_Arcloss` is not included in the models directory and also the `audio_processing.py` has incorrect path with wrong slash used.
Do look into it!
Below are the some reference to above error

ERROR TRACE:
`
  onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from 
  C:\Users\OnlinePage\.conda\envs\myenv1\Lib\site- 
  packages\eff_word_net\models/resnet_50_arc/slim_93%_accuracy_72.7390%.onnx failed:Load model 
  C:\Users\OnlinePage\.conda\envs\myenv1\Lib\site- 
  packages\eff_word_net\models/resnet_50_arc/slim_93%_accuracy_72.7390%.onnx failed. File doesn't exist

`

Model is not there in the models directory: 😕
![image](https://user-images.githubusercontent.com/61045650/232075712-a6d4f011-00ca-47d1-9aff-aee09947d2e3.png)

**Comment by TheSeriousProgrammer** [comment]
my bad, probably got missed in the pypi build will look into it, for now you can try it out through git clone

**Comment by TheSeriousProgrammer** [comment]
That was a typo in the example , can you check README.md again

**Comment by TheSeriousProgrammer** [comment]
Model is included as well in the pip package now

**Comment by TheSeriousProgrammer** [comment]
Thanks for the kind words

The model is fundamentally a classifier which can only look for a specific window of data

In this case 1.5 second long audio

But if we split the audio simply into 1.5 second long chunks , there is a possibility where a hotword utterance gets caught exactly between 2 chunks, and when that happens hot word will not be detected.

To avoid this sliding window is implemented where the the extracted audio chunks will be overlapping

We now face the problem of multiple detections per utterance. when a single hot word utterance is present exactly in the overlapping area of 2 or more overlapping chunks 

The sliding_window_secs parameter controls the degree of overlap

We are currently toying with different approaches to overcome the problem

one solution is to increase the relaxation time (I.e min time required between 2 utterances), you can toy around with this value in the constructor of your hotworddetector

**Comment by TheSeriousProgrammer** [comment]
I am currently closing this issue as the problems in this issue has been resolved
