### ISSUE TITLE
Release the training code of new model.

### ISSUE THREAD

**Issue by yongliang-wu** [Ant-Brain/EfficientWord-Net#34]
Hello, the new model resnet50 works really good for me, but the size is still too big to deploy at edge device. Would you please release the training code and the new dataset link?

**Comment by TheSeriousProgrammer** [comment]
Thanks for the kind words. Here is the training code https://github.com/Ant-Brain/EfficientWord-Net-Trainer.git
I have not found time to clean it yet , but here it is . The starting point of the code is simple_trainer.py

It is in our plans to create a MCU compatible version of the same. It would be helpful if you could share some of your insights in creating a trimmed down MCU compatible version of the same

**Comment by Holly-Max** [comment]
Ok, I have found the code. But would you mind to provide the dataset?  And maybe I can help u to clean them if I can train it.

**Comment by TheSeriousProgrammer** [comment]
a sad update. The dataset was present in my academic instance and it was taken down. will try to recreate it with the available scripts

**Comment by TheSeriousProgrammer** [comment]
You can make use of this for now , ml commons have uploaded the dataset with train test and validation in huggingface https://huggingface.co/datasets/MLCommons/ml_spoken_words/tree/main/data/wav/en

**Comment by Holly-Max** [comment]
ok, thanks!
