### ISSUE TITLE
Hotword detection triggers the moment any sound is being playd, even with the default models

### ISSUE THREAD

**Issue by TrackLab** [Ant-Brain/EfficientWord-Net#7]
So I've been trying to make a custom hotwork. But after seeing it trigger all the time, the moment any kind of sound is being recorded, I decided to use a default one, like "brightness", "mobile", "google", etc.

They all trigger immediatley. Using the default values for the HotWordDetector, by the way.
Any clue why? It seemed to have worked great in your video presentation. 

Not using a cheap ass microphone by the way.

**Comment by TheSeriousProgrammer** [comment]
are you using custom confidence scores? can you share your code snippet if you don't mind ?

**Comment by TrackLab** [comment]
I already said in my issue post that I am using the very default project. Default values, default threshold, default models included in the project. Nothing about this is custom.

**Comment by TheSeriousProgrammer** [comment]
can you send a video recording of cli output when you run "python3 -m eff_word_net.engine", where you try pronouncing google , alexa , etc..

**Comment by Fidode07** [comment]
Same Issue

**Comment by aman-17** [comment]
> I already said in my issue post that I am using the very default project. Default values, default threshold, default models included in the project. Nothing about this is custom.

Hey there, can you increase the threshold value and try it? Because few hotwords needs higher threshold values to shut false positives.

**Comment by TrackLab** [comment]
> > I already said in my issue post that I am using the very default project. Default values, default threshold, default models included in the project. Nothing about this is custom.
> 
> Hey there, can you increase the threshold value and try it? Because few hotwords need higher threshold values to shut false positives.

I already did. Even with 0.99 it triggers alot of times false positive. With a custom model using the IBM Sound generation it false triggers even more often. 
Also worth noting, when it triggers, it prints "DETECTED!" several times after each other, as if it triggers 5 times per single trigger.

**Comment by aman-17** [comment]
Thanks for the reply, we will look into it and update you shortly.

**Comment by TheSeriousProgrammer** [comment]
> > > I already said in my issue post that I am using the very default project. Default values, default threshold, default models included in the project. Nothing about this is custom.
> > 
> > 
> > Hey there, can you increase the threshold value and try it? Because few hotwords need higher threshold values to shut false positives.
> 
> I already did. Even with 0.99 it triggers alot of times false positive. With a custom model using the IBM Sound generation it false triggers even more often. Also worth noting, when it triggers, it prints "DETECTED!" several times after each other, as if it triggers 5 times per single trigger.

This is actaully an expected thing, the network works over sliding windows of the audio stream, so for every utterance , there will be 4to5 triggers, this can be temporarily mitigated by treating the triggers as square waves. I was a bit a lazy to add it in the library. In 2-3 days I'll make a patch and update

**Comment by TheSeriousProgrammer** [comment]
Made some major changes in HotwordDetector instance, to make sure that ther should be only one trigger per utterance. Made few with assumptions such as no utterance will be longer than a second and a there will be atleast 800ms window between 2 utterances , update your python package and try running the demo code. Let me know if it works good

**Comment by TheSeriousProgrammer** [comment]
Due to inactivitiy I am closing this issue and moreover the patch is pushed . Feel free to reopen it @TrackLab
